CREATE TABLE "ADDRESS"
 ( "ID" NUMBER NOT NULL ENABLE,
 "STREET" VARCHAR2(50),
 "CITY" VARCHAR2(50),
 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID") ENABLE,
 CONSTRAINT "ADDRESS_FK" FOREIGN KEY ("ID")
 REFERENCES "CUSTOMER" ("ID") ENABLE
 )
/
